# NetBase etherpad container
#
# ETHERPAD_TITLE: Title of the Etherpad Lite instance. Defaults to "Etherpad".
# ETHERPAD_PORT: Port of the Etherpad Lite instance. Defaults to 9001.
# ETHERPAD_ADMIN_PASSWORD: If set, an admin account is enabled for Etherpad, and the /admin/ interface is accessible via it.
# ETHERPAD_ADMIN_USER: If the admin password is set, this defaults to "admin". Otherwise the user can set it to another username.
# ETHERPAD_DB_TYPE: Type of databse to use. Defaults to mysql.
# ETHERPAD_DB_HOST: Hostname of the database to use. Defaults to mysql.
# ETHERPAD_DB_USER: By default Etherpad Lite will attempt to connect as root to the database container.
# ETHERPAD_DB_PASSWORD: Password to use, mandatory. If legacy links are used and ETHERPAD_DB_USER is root, then MYSQL_ENV_MYSQL_ROOT_PASSWORD is automatically used.
# ETHERPAD_DB_PASSWORD_FILE: MySQL password to use, replace ETHERPAD_DB_PASSWORD when using Docker secrets.
# ETHERPAD_DB_NAME: The database to use. Defaults to etherpad. If the database is not available, it will be created when the container is launched 
#	(only if the database type is either mysql or postgres, and the user need to have the right to create the database).
# ETHERPAD_DB_CHARSET: The charset to use. Defaults to utf8mb4.
# ETHERPAD_API_KEY: if file APIKEY.txt is missing, the variable value is used to provision it

version: '3'


services:

  etherpad-core:
    image: 'tvelocity/etherpad-lite:latest'
    # This container doesnt seem to use version numbering
    hostname: etherpad-core
    container_name: etherpad-core
    restart: unless-stopped
    ports:
      - '9001:9001'
    volumes:
       - './plugins:/opt/etherpad-lite/node_modules'
    environment:
      - ETHERPAD_DB_HOST=etherpad-db
      - ETHERPAD_DB_PASSWORD=QQDPB6vp9-WDhbdqIFZu3EzZmnN1y_-R
      - ETHERPAD_ADMIN_PASSWORD=admin
    depends_on:
      - etherpad-db

  etherpad-db:
    image: 'mysql:5'
#    image: 'mysql'
# Not using the default mysql image (currently 8.0) because it results in errors
#    command: mysqld --default-authentication-plugin=mysql_native_password
    hostname: etherpad-db
    container_name: etherpad-db
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - '../../data/etherpad:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=QQDPB6vp9-WDhbdqIFZu3EzZmnN1y_-R
