# NetBase portainer container

version: '3'


services:

  portainer:
    image: 'portainer/portainer:1.24.1-alpine'
    hostname: portainer
    container_name: portainer
    restart: unless-stopped
    command: --no-auth -H unix:///var/run/docker.sock
    ports:
      - '9000:9000'
    volumes:
      - '../../data/portainer:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
