# NetBase wiki container

version: '3'


services:

  wiki:
    image: 'bitnami/dokuwiki:20200729.0.0'
    hostname: wiki
    container_name: wiki
    restart: unless-stopped
    user: root
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './netbase-help:/opt/bitnami/dokuwiki/netbase:ro'
      - '../../data/wiki:/bitnami/dokuwiki'
    environment:
      - DOKUWIKI_USERNAME=admin
      - DOKUWIKI_PASSWORD=admin
      - DOKUWIKI_FULL_NAME=admin
      - DOKUWIKI_WIKI_NAME=NetBase Wiki
